/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u8AgdetFK",
    "aws_user_pools_web_client_id": "57k85ifbh1k97adua1uuleqgq5",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "LumiapirekogdevEndpoint69B7D6A1",
            "endpoint": " https://dyq0v4lcs0.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
